application:
  subdomain: 88jizhang
  public_path:
    - /
  background_task: true
  multi_instance: false
  upstreams:
    - location: /
      backend: http://88jizhang:5188/
services:
  88jizhang:
    # upstream: crpi-btxs8xhps2iaw65e.cn-hangzhou.personal.cr.aliyuncs.com/88jizhang/88jizhang:v1.0.13
    image: registry.lazycat.cloud/czyt/88jizhang/88jizhang:b89bca69a9ff28c0
    environment:
      - TZ=Asia/Shanghai
    binds:
      - /lzcapp/var/data:/app/data
      - /lzcapp/var/zhangdan-picture:/app/zhangbenpicture/zhangdan-picture
    setup_script: |
      if [ ! -f /app/data/jizhang.db ];then
        cp -f /lzcapp/pkg/content/jizhang.db /app/data/jizhang.db
      fi
      rm -rf /app/jizhang.db
      ln -s /app/data/jizhang.db /app/jizhang.db
